# notebook for data split and transform  

In [1]:
import pandas as pd
import numpy as np

# load raw data

In [14]:
raw_data_path = '../../data/01_raw/financial_fraud/bs140513_032310.csv'

In [15]:
raw_trans_data = pd.read_csv(raw_data_path)

In [16]:
raw_trans_data.shape

(594643, 10)

In [17]:
raw_trans_data.head(10)

step       customer  age gender zipcodeOri       merchant zipMerchant  \
0     0  'C1093826151'  '4'    'M'    '28007'   'M348934600'     '28007'   
1     0   'C352968107'  '2'    'M'    '28007'   'M348934600'     '28007'   
2     0  'C2054744914'  '4'    'F'    '28007'  'M1823072687'     '28007'   
3     0  'C1760612790'  '3'    'M'    '28007'   'M348934600'     '28007'   
4     0   'C757503768'  '5'    'M'    '28007'   'M348934600'     '28007'   
5     0  'C1315400589'  '3'    'F'    '28007'   'M348934600'     '28007'   
6     0   'C765155274'  '1'    'F'    '28007'   'M348934600'     '28007'   
7     0   'C202531238'  '4'    'F'    '28007'   'M348934600'     '28007'   
8     0   'C105845174'  '3'    'M'    '28007'   'M348934600'     '28007'   
9     0    'C39858251'  '5'    'F'    '28007'   'M348934600'     '28007'   

              category  amount  fraud  
0  'es_transportation'    4.55      0  
1  'es_transportation'   39.68      0  
2  'es_transportation'   26.89      0  
3  'es_transportation'   17.25      0  
4  'es_transportation'   35.72      0  
5  'es_transportation'   25.81      0  
6  'es_transportation'    9.10      0  
7  'es_transportation'   21.17      0  
8  'es_transportation'   32.40      0  
9  'es_transportation'   35.40      0

In [20]:
raw_trans_data.tail(10)

step       customer  age gender zipcodeOri       merchant zipMerchant  \
594633   179  'C1039390058'  '4'    'M'    '28007'    'M45060432'     '28007'   
594634   179   'C728039227'  '6'    'M'    '28007'   'M348934600'     '28007'   
594635   179   'C728039227'  '6'    'M'    '28007'  'M1823072687'     '28007'   
594636   179  'C1904086644'  '5'    'F'    '28007'  'M1823072687'     '28007'   
594637   179   'C748358246'  '2'    'M'    '28007'  'M1823072687'     '28007'   
594638   179  'C1753498738'  '3'    'F'    '28007'  'M1823072687'     '28007'   
594639   179   'C650108285'  '4'    'F'    '28007'  'M1823072687'     '28007'   
594640   179   'C123623130'  '2'    'F'    '28007'   'M349281107'     '28007'   
594641   179  'C1499363341'  '5'    'M'    '28007'  'M1823072687'     '28007'   
594642   179   'C616528518'  '4'    'F'    '28007'  'M1823072687'     '28007'   

                   category  amount  fraud  
594633   'es_hotelservices'  190.31      0  
594634  'es_transportation'   27.93      0  
594635  'es_transportation'   30.04      0  
594636  'es_transportation'   28.93      0  
594637  'es_transportation'   51.17      0  
594638  'es_transportation'   20.53      0  
594639  'es_transportation'   50.73      0  
594640         'es_fashion'   22.44      0  
594641  'es_transportation'   14.46      0  
594642  'es_transportation'   26.93      0

In [18]:
raw_trans_data_sorted = raw_trans_data.sort_values(by='step').reset_index(drop=True)

In [19]:
raw_trans_data_sorted

step       customer  age gender zipcodeOri       merchant zipMerchant  \
0          0  'C1093826151'  '4'    'M'    '28007'   'M348934600'     '28007'   
1          0  'C1799882713'  '1'    'F'    '28007'  'M1823072687'     '28007'   
2          0  'C1663641926'  '6'    'F'    '28007'   'M348934600'     '28007'   
3          0  'C1255149927'  '2'    'M'    '28007'   'M348934600'     '28007'   
4          0  'C1666444221'  '3'    'M'    '28007'   'M348934600'     '28007'   
...      ...            ...  ...    ...        ...            ...         ...   
594638   179  'C1861613802'  '6'    'M'    '28007'  'M1823072687'     '28007'   
594639   179   'C272752096'  '3'    'F'    '28007'  'M1823072687'     '28007'   
594640   179  'C1501124312'  '4'    'M'    '28007'  'M1823072687'     '28007'   
594641   179  'C1738944491'  '2'    'M'    '28007'  'M1823072687'     '28007'   
594642   179   'C616528518'  '4'    'F'    '28007'  'M1823072687'     '28007'   

                   category  amount  fraud  
0       'es_transportation'    4.55      0  
1       'es_transportation'   16.71      0  
2       'es_transportation'   22.70      0  
3       'es_transportation'   26.04      0  
4       'es_transportation'   27.27      0  
...                     ...     ...    ...  
594638  'es_transportation'   26.47      0  
594639  'es_transportation'   14.02      0  
594640  'es_transportation'   14.96      0  
594641  'es_transportation'   13.05      0  
594642  'es_transportation'   26.93      0  

[594643 rows x 10 columns]

In [26]:
raw_net_data_path = '../../data/01_raw/financial_fraud/bsNET140513_032310.csv'

In [27]:
raw_net_trans_data = pd.read_csv(raw_net_data_path)

In [28]:
raw_net_trans_data.shape

(594643, 5)

In [29]:
raw_net_trans_data.head(10)

Source         Target  Weight            typeTrans  fraud
0  'C1093826151'   'M348934600'    4.55  'es_transportation'      0
1   'C352968107'   'M348934600'   39.68  'es_transportation'      0
2  'C2054744914'  'M1823072687'   26.89  'es_transportation'      0
3  'C1760612790'   'M348934600'   17.25  'es_transportation'      0
4   'C757503768'   'M348934600'   35.72  'es_transportation'      0
5  'C1315400589'   'M348934600'   25.81  'es_transportation'      0
6   'C765155274'   'M348934600'    9.10  'es_transportation'      0
7   'C202531238'   'M348934600'   21.17  'es_transportation'      0
8   'C105845174'   'M348934600'   32.40  'es_transportation'      0
9    'C39858251'   'M348934600'   35.40  'es_transportation'      0

# process edge data

In [30]:
edges = raw_net_trans_data[['Source','Target']]

In [31]:
edges

Source         Target
0       'C1093826151'   'M348934600'
1        'C352968107'   'M348934600'
2       'C2054744914'  'M1823072687'
3       'C1760612790'   'M348934600'
4        'C757503768'   'M348934600'
...               ...            ...
594638  'C1753498738'  'M1823072687'
594639   'C650108285'  'M1823072687'
594640   'C123623130'   'M349281107'
594641  'C1499363341'  'M1823072687'
594642   'C616528518'  'M1823072687'

[594643 rows x 2 columns]

In [32]:
edges = edges.loc[edges.Source!=edges.Target]
edges

Source         Target
0       'C1093826151'   'M348934600'
1        'C352968107'   'M348934600'
2       'C2054744914'  'M1823072687'
3       'C1760612790'   'M348934600'
4        'C757503768'   'M348934600'
...               ...            ...
594638  'C1753498738'  'M1823072687'
594639   'C650108285'  'M1823072687'
594640   'C123623130'   'M349281107'
594641  'C1499363341'  'M1823072687'
594642   'C616528518'  'M1823072687'

[594643 rows x 2 columns]

In [33]:
edges.shape

(594643, 2)

In [34]:
edges = np.array(edges)

In [35]:
edges, edges.shape

(array([["'C1093826151'", "'M348934600'"],
        ["'C352968107'", "'M348934600'"],
        ["'C2054744914'", "'M1823072687'"],
        ...,
        ["'C123623130'", "'M349281107'"],
        ["'C1499363341'", "'M1823072687'"],
        ["'C616528518'", "'M1823072687'"]], dtype=object),
 (594643, 2))

### dedupe edge

In [37]:
aa, idx = np.unique(edges.tolist(), return_index=True, axis=0) #dedupe 

In [38]:
len(aa) #many duplicated edges 

47132

In [39]:
len(idx)

47132

In [41]:
aa

array([["'C1000148617'", "'M1053599405'"],
       ["'C1000148617'", "'M1400236507'"],
       ["'C1000148617'", "'M1741626453'"],
       ...,
       ["'C999723254'", "'M480139044'"],
       ["'C999723254'", "'M855959430'"],
       ["'C999723254'", "'M85975013'"]], dtype='<U13')

In [42]:
idx

array([570947, 157297, 105386, ..., 317649, 133139, 279289])

In [43]:
np.sort(idx)

array([     0,      1,      2, ..., 594622, 594633, 594640])

In [44]:
edges = edges[np.sort(idx)]

In [46]:
edges, edges.shape

(array([["'C1093826151'", "'M348934600'"],
        ["'C352968107'", "'M348934600'"],
        ["'C2054744914'", "'M1823072687'"],
        ...,
        ["'C300052027'", "'M1053599405'"],
        ["'C1039390058'", "'M45060432'"],
        ["'C123623130'", "'M349281107'"]], dtype=object),
 (47132, 2))

In [47]:
vertexs, edges_1d = np.unique(edges, return_inverse=True)

In [50]:
vertexs, len(vertexs)

(array(["'C1000148617'", "'C100045114'", "'C1000699316'", ...,
        "'M933210764'", "'M97925176'", "'M980657600'"], dtype=object),
 4162)

In [71]:
vertex_to_id = {}
for i,vertex in enumerate(vertexs):
    vertex_to_id.setdefault(vertex,i)
    

In [72]:
vertex_to_id

{"'C1000148617'": 0,
 "'C100045114'": 1,
 "'C1000699316'": 2,
 "'C1001065306'": 3,
 "'C1002658784'": 4,
 "'C1002759277'": 5,
 "'C1004109477'": 6,
 "'C1004300450'": 7,
 "'C1004532392'": 8,
 "'C1005126300'": 9,
 "'C1005495267'": 10,
 "'C1005806982'": 11,
 "'C1006176917'": 12,
 "'C1007572087'": 13,
 "'C1007790716'": 14,
 "'C1008918174'": 15,
 "'C1009080922'": 16,
 "'C100992504'": 17,
 "'C10105795'": 18,
 "'C1010589026'": 19,
 "'C1010865894'": 20,
 "'C1010936270'": 21,
 "'C1011693897'": 22,
 "'C1012876398'": 23,
 "'C1013199152'": 24,
 "'C1013313546'": 25,
 "'C1014010834'": 26,
 "'C1014124305'": 27,
 "'C1014313887'": 28,
 "'C1014347664'": 29,
 "'C1014783484'": 30,
 "'C1014847580'": 31,
 "'C1017469037'": 32,
 "'C1017941602'": 33,
 "'C1018153896'": 34,
 "'C1018388493'": 35,
 "'C1018653381'": 36,
 "'C1018783569'": 37,
 "'C1018979501'": 38,
 "'C1019071188'": 39,
 "'C1019678929'": 40,
 "'C1020019215'": 41,
 "'C102010508'": 42,
 "'C1020192133'": 43,
 "'C1020355960'": 44,
 "'C1021409246'": 45,
 "'

In [99]:
vertex_to_id_df=pd.DataFrame.from_dict(vertex_to_id,  orient='index', columns=['idx'])

In [100]:
vertex_to_id_df

idx
'C1000148617'     0
'C100045114'      1
'C1000699316'     2
'C1001065306'     3
'C1002658784'     4
...             ...
'M85975013'    4157
'M923029380'   4158
'M933210764'   4159
'M97925176'    4160
'M980657600'   4161

[4162 rows x 1 columns]

In [52]:
edges_1d,  len(edges_1d)

(array([ 210, 4142, 2753, ..., 4145,  529, 4143]), 94264)

In [53]:
edges_idx = np.reshape(edges_1d, [-1, 2])

In [54]:
edges_idx, len(edges_idx)

(array([[ 210, 4142],
        [2753, 4142],
        [2285, 4130],
        ...,
        [2646, 4112],
        [  86, 4145],
        [ 529, 4143]]),
 47132)

In [94]:
type(edges_idx)

numpy.ndarray

In [58]:
#see if the indexes are correct 
(vertexs[210], vertexs[4142]), (vertexs[2753], vertexs[4142]),(vertexs[2285], vertexs[4130])

(("'C1093826151'", "'M348934600'"),
 ("'C352968107'", "'M348934600'"),
 ("'C2054744914'", "'M1823072687'"))

In [55]:
print('vertex:', len(vertexs), 'edge:', len(edges_idx))

vertex: 4162  edge:  47132


# find labels for the edge

In [60]:
from tqdm import tqdm

In [80]:
edge_label = {}
for idx, row in raw_net_trans_data.iterrows():
    if(idx%10000==0):
        print(idx)
    #print(row['Source'],row['Target'],row['fraud'])
    edge_label.setdefault((vertex_to_id[row['Source']],vertex_to_id[row['Target']]), []).append(row['fraud'])

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000


In [82]:
edge_label

{(210, 4142): [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 (2753, 4142): [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  

In [83]:
edge_label_unique = {k: np.unique(edge_label[k]) for k in edge_label}

In [90]:
edge_label_unique

{(210, 4142): array([0]),
 (2753, 4142): array([0]),
 (2285, 4130): array([0]),
 (1650, 4142): array([0]),
 (3585, 4142): array([0]),
 (694, 4142): array([0]),
 (3609, 4142): array([0]),
 (2227, 4142): array([0]),
 (126, 4142): array([0]),
 (2853, 4142): array([0]),
 (4085, 4142): array([0]),
 (1199, 4130): array([0]),
 (3317, 4148): array([0]),
 (1869, 4130): array([0]),
 (3049, 4142): array([0]),
 (2036, 4142): array([0]),
 (463, 4130): array([0]),
 (3752, 4142): array([0]),
 (1943, 4142): array([0]),
 (553, 4142): array([0]),
 (1483, 4142): array([0]),
 (1508, 4142): array([0]),
 (4083, 4142): array([0]),
 (3714, 4142): array([0]),
 (1346, 4142): array([0]),
 (1890, 4142): array([0]),
 (2581, 4142): array([0]),
 (3048, 4142): array([0]),
 (3152, 4142): array([0]),
 (1232, 4142): array([0]),
 (609, 4142): array([0]),
 (1273, 4130): array([0]),
 (4109, 4142): array([0]),
 (894, 4142): array([0]),
 (375, 4142): array([0]),
 (3500, 4142): array([0]),
 (365, 4142): array([0]),
 (3269, 41

In [87]:
edge_label_two_labels = {k: edge_label_unique[k] for k in edge_label_unique if len(edge_label_unique[k])>1 }

In [89]:
edge_label_two_labels, len(edge_label_two_labels)

({(3219, 4146): array([0, 1]),
  (723, 4146): array([0, 1]),
  (178, 4161): array([0, 1]),
  (1782, 4161): array([0, 1]),
  (2331, 4122): array([0, 1]),
  (969, 4114): array([0, 1]),
  (1478, 4161): array([0, 1]),
  (405, 4126): array([0, 1]),
  (2844, 4161): array([0, 1]),
  (2146, 4155): array([0, 1]),
  (2918, 4114): array([0, 1]),
  (169, 4146): array([0, 1]),
  (2695, 4122): array([0, 1]),
  (232, 4122): array([0, 1]),
  (3716, 4122): array([0, 1]),
  (1061, 4139): array([0, 1]),
  (3164, 4139): array([0, 1]),
  (3660, 4139): array([0, 1]),
  (2231, 4122): array([0, 1]),
  (4045, 4122): array([0, 1]),
  (2804, 4161): array([0, 1]),
  (2744, 4114): array([0, 1]),
  (1451, 4151): array([0, 1]),
  (473, 4146): array([0, 1]),
  (2341, 4146): array([0, 1]),
  (86, 4155): array([0, 1]),
  (3955, 4146): array([0, 1]),
  (3111, 4161): array([0, 1]),
  (2532, 4155): array([0, 1]),
  (1850, 4139): array([0, 1]),
  (2094, 4146): array([0, 1]),
  (1184, 4146): array([0, 1]),
  (2215, 4149): a

In [91]:
edge_label_postprocessed = {k: max(edge_label_unique[k]) for k in edge_label_unique}

In [93]:
len(edge_label), len(edge_label_unique),len(edge_label_two_labels), len(edge_label_postprocessed) #only 1108 out of 47132 edges had flipped labels 

(47132, 47132, 1108, 47132)

In [101]:
edge_label_postprocessed

{(210, 4142): 0,
 (2753, 4142): 0,
 (2285, 4130): 0,
 (1650, 4142): 0,
 (3585, 4142): 0,
 (694, 4142): 0,
 (3609, 4142): 0,
 (2227, 4142): 0,
 (126, 4142): 0,
 (2853, 4142): 0,
 (4085, 4142): 0,
 (1199, 4130): 0,
 (3317, 4148): 0,
 (1869, 4130): 0,
 (3049, 4142): 0,
 (2036, 4142): 0,
 (463, 4130): 0,
 (3752, 4142): 0,
 (1943, 4142): 0,
 (553, 4142): 0,
 (1483, 4142): 0,
 (1508, 4142): 0,
 (4083, 4142): 0,
 (3714, 4142): 0,
 (1346, 4142): 0,
 (1890, 4142): 0,
 (2581, 4142): 0,
 (3048, 4142): 0,
 (3152, 4142): 0,
 (1232, 4142): 0,
 (609, 4142): 0,
 (1273, 4130): 0,
 (4109, 4142): 0,
 (894, 4142): 0,
 (375, 4142): 0,
 (3500, 4142): 0,
 (365, 4142): 0,
 (3269, 4130): 0,
 (1675, 4142): 0,
 (4102, 4142): 0,
 (921, 4134): 0,
 (2713, 4130): 0,
 (1372, 4112): 0,
 (4105, 4142): 0,
 (721, 4142): 0,
 (3071, 4142): 0,
 (3756, 4142): 0,
 (1510, 4130): 0,
 (1473, 4142): 0,
 (2375, 4142): 0,
 (1878, 4130): 0,
 (3723, 4142): 0,
 (84, 4142): 0,
 (2736, 4142): 0,
 (3343, 4142): 0,
 (2040, 4142): 0,
 (403

In [102]:
edge_label_postprocessed_df=pd.DataFrame.from_dict(edge_label_postprocessed,  orient='index', columns=['label'])

In [103]:
edge_label_postprocessed_df

label
(210, 4142)       0
(2753, 4142)      0
(2285, 4130)      0
(1650, 4142)      0
(3585, 4142)      0
...             ...
(2863, 4128)      0
(3197, 4143)      0
(2646, 4112)      0
(86, 4145)        0
(529, 4143)       0

[47132 rows x 1 columns]

In [105]:
edge_label_postprocessed_df['label'].value_counts(normalize=True)

0    0.903675
1    0.096325
Name: label, dtype: float64